version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: psql-backup
    container_name: psql-backup
    ports:
      - 4444:80
    restart: always
    environment:
      - AZURE_BLOBS_CONNECTION=DefaultEndpointsProtocol=https;AccountName=vizage;AccountKey=Y53ELMSKwZG6BFe2MzXTwCXbs4yMYju7Aoac6olWLD3ZPSd6+q++mSKqaW7XmkZewcG7IMDFZ/UO+AStFKkgCA==;EndpointSuffix=core.windows.net
      - AZURE_BLOBS_CONTAINER=dev
      - BACKUP_REPEAT_IN_HOURS=24
      - HOST=192.46.212.10
      - PORT=5432
      - USER_NAME=postgres
      - PASSWORD=GSMakMOOUM9x9A8K6q3LsElUJbu9beB4
      - BACKUP_FILE_PATH=/var/www
      - DATABASES=Vizage-[dev]
      - PG_DUMP_PATH=/usr/bin/pg_dump
